# Site settings
title: Song Chunxiao
email: songchunxiao.jhu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All rights reserved @ Song Chunxiao
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://skyey.co" # the base hostname & protocol for your site
github_username:  songchunxiao

# Build settings
markdown: kramdown
